import numpy as np
a = np.arange(1, 21)
print("First 5 elements:")
print(a[:5])
print("Last 5 elements:")
print(a[-5:])
print("Alternate elements:")
print(a[::2])
print("Reverse order:")
print(a[::-1])